apiVersion: v1
kind: Service
metadata:
  name: ccms-backend
  namespace: default
  labels:
    app: ccms-backend
spec:
  type: ClusterIP
  selector:
    app: ccms-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
